attention_dropout: 0
balanced: false
clean_prefix_expr: true
dropout: 0
emb_dim: 1024
env_name: char_sp
int_base: 10
leaf_probs: 0.75,0,0.25,0
max_int: 5
max_len: 512
max_ops: 15
max_ops_G: 15
n_coefficients: 0
n_dec_layers: 6
n_enc_layers: 6
n_heads: 8
n_variables: 1
operators: add:10,sub:3,mul:10,div:5,sqrt:4,pow2:4,pow3:2,pow4:1,pow5:1,ln:4,exp:4,sin:4,cos:4,tan:4,asin:1,acos:1,atan:1,sinh:1,cosh:1,tanh:1,asinh:1,acosh:1,atanh:1
positive: true
precision: 10
rewrite_functions: ''
share_inout_emb: true
sinusoidal_embeddings: false
tasks: prim_fwd
